# TODO: create config files for formatting/linting arguments
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-toml

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args:
        - "--line-length=100"

  - repo: local
    hooks:
    - id: flake8
      name: flake8
      language: python
      entry: flake8
      files: ".*.py$"
      args:
        - "--max-line-length=100"
        - "--exclude=kscope/__init__.py"

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.942
  #   hooks:
  #   - id: mypy
  #     args: [--namespace-packages, --explicit-package-bases]
  #     additional_dependencies: [types-python-dateutil==2.8.8, types-PyYAML==6.0.5]

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      language: python
      entry: pylint
      files: ".*.py$"
      exclude: fsd
      args:
        - "--max-line-length=100"
        - "--fail-under=8"

  # - repo: local
  #   hooks:
  #   - id: pytest
  #     name: pytest
  #     entry: pytest -m "not integration_test"
  #     language: system
  #     pass_filenames: false
  #     always_run: true
